FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

COPY ./src/CS/AspNetCoreApp/Web .

RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app

COPY  --from=build-env /app/out .

ENTRYPOINT [ "dotnet", "Aspnet.Frontend.Ui.dll" ]