FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /api

COPY ./src/CS/AspNetCoreApp/Api .

RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /api

COPY --from=build-env /api/out .

ENTRYPOINT [ "dotnet", "Aspnet.Backend.Api.dll" ]