FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /Job

COPY ./src/CS/Job .

RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /Job

COPY --from=build-env /Job/out .

ENTRYPOINT ["dotnet", "Job.dll"]